/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dbe4e7",
        "surface-container-highest": "#dbe4e7",
        "on-primary": "#f7f7ff",
        "tertiary-dim": "#51506c",
        "error-container": "#fe8983",
        "inverse-surface": "#0c0f10",
        "inverse-on-surface": "#9b9d9e",
        "on-surface-variant": "#586064",
        "on-secondary-fixed": "#264350",
        "error": "#9f403d",
        "surface": "#f8f9fa",
        "tertiary-fixed-dim": "#ceccec",
        "tertiary-container": "#dcd9fa",
        "surface-container-high": "#e3e9ec",
        "outline-variant": "#abb3b7",
        "on-error-container": "#752121",
        "on-secondary": "#f3faff",
        "on-surface": "#2b3437",
        "surface-container-low": "#f1f4f6",
        "secondary-container": "#c9e7f7",
        "on-secondary-container": "#395663",
        "inverse-primary": "#84acf2",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#c0d5ff",
        "on-primary-fixed": "#053e7d",
        "surface-container": "#eaeff1",
        "primary-dim": "#255292",
        "primary-container": "#d6e3ff",
        "tertiary-fixed": "#dcd9fa",
        "error-dim": "#4e0309",
        "outline": "#737c7f",
        "on-background": "#2b3437",
        "secondary-fixed-dim": "#bbd9e9",
        "background": "#f8f9fa",
        "on-tertiary": "#fbf7ff",
        "on-tertiary-container": "#4d4c67",
        "surface-tint": "#335e9f",
        "surface-dim": "#d1dce0",
        "on-tertiary-fixed-variant": "#565571",
        "tertiary": "#5d5c78",
        "on-tertiary-fixed": "#3a3953",
        "on-secondary-fixed-variant": "#435f6d",
        "on-primary-container": "#245191",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#c9e7f7",
        "secondary": "#466370",
        "primary": "#335e9f",
        "surface-bright": "#f8f9fa",
        "secondary-dim": "#3a5764",
        "on-error": "#fff7f6",
        "on-primary-fixed-variant": "#305b9c"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "manrope": ["Manrope"],
        "inter": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
